# Generated by Django 5.1.3 on 2026-06-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En Revisión'), ('cotizado', 'Cotizado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='recibido', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
