# Generated by Django 6.0.6 on 2026-07-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('recibido', 'Recibido'), ('en_revision', 'En Revisión'), ('cotizado', 'Cotizado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20),
        ),
    ]
