# Generated by Django 6.0.6 on 2026-07-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
